# Generated by Django 3.0 on 2020-07-18 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0002_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonatedFood',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('foodStatus', models.CharField(choices=[('Uncooked', 'Uncooked'), ('Cooked', 'Cooked')], max_length=200, null=True)),
                ('foodDescription', models.CharField(max_length=500, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonatedCloth',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('clothType', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True)),
                ('clothDescription', models.CharField(max_length=500, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
