# Generated by Django 3.0 on 2020-07-18 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_donatedcloth_donatedfood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donatedcloth',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='donatedfood',
            name='Date',
        ),
        migrations.AddField(
            model_name='donatedcloth',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='donatedfood',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contact',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
