# Generated by Django 3.0.4 on 2020-07-19 13:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20200719_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributioncentre',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('distributionCentre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.DistributionCentre')),
                ('donatedCloth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.DonatedCloth')),
                ('donatedFood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.DonatedFood')),
            ],
        ),
    ]
