# Generated by Django 3.0.4 on 2020-07-19 14:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20200719_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted')], max_length=200, null=True)),
                ('distributionCentre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.DistributionCentre')),
                ('donatedCloth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.DonatedCloth')),
                ('donatedFood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.DonatedFood')),
            ],
        ),
        migrations.DeleteModel(
            name='Donations',
        ),
    ]
