# Generated by Django 3.0 on 2020-07-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20200719_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='user',
        ),
        migrations.AddField(
            model_name='feed',
            name='user1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='feed',
            field=models.TextField(null=True),
        ),
    ]
