# Generated by Django 3.0 on 2020-07-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20200719_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatedcloth',
            name='pin',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='donatedfood',
            name='pin',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
