# Generated by Django 3.0.8 on 2020-07-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='email',
        ),
        migrations.AddField(
            model_name='notification',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='type1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
