# Generated by Django 3.0.4 on 2020-07-25 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0014_notification_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonatedOther',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('pin', models.CharField(max_length=10, null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('otherDescription', models.CharField(max_length=500, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
