# Generated by Django 3.0.8 on 2020-07-26 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20200719_1939'),
        ('mysite', '0015_donatedother'),
    ]

    operations = [
    ]
